### ISSUE TITLE
Traceback when launching app contains error with itsdangerous

### ISSUE THREAD

**Issue by jlerman44** [dudil/fastapi_msal#1] opened 2021-06-03 06:44 UTC
I followed the instructions pretty carefully, but when launching the app and visiting the site I get 

kithara_base_1  | ERROR:    Exception in ASGI application
kithara_base_1  | Traceback (most recent call last):
kithara_base_1  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 371, in run_asgi
kithara_base_1  |     result = await app(self.scope, self.receive, self.send)
kithara_base_1  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
kithara_base_1  |     return await self.app(scope, receive, send)
kithara_base_1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
kithara_base_1  |     await super().__call__(scope, receive, send)
kithara_base_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
kithara_base_1  |     await self.middleware_stack(scope, receive, send)
kithara_base_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
kithara_base_1  |     raise exc from None
kithara_base_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
kithara_base_1  |     await self.app(scope, receive, _send)
kithara_base_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/sessions.py", line 42, in __call__
kithara_base_1  |     data = self.signer.unsign(data, max_age=self.max_age)
kithara_base_1  |   File "/usr/local/lib/python3.9/site-packages/itsdangerous/timed.py", line 110, in unsign
kithara_base_1  |     raise sig_error
kithara_base_1  |   File "/usr/local/lib/python3.9/site-packages/itsdangerous/timed.py", line 95, in unsign
kithara_base_1  |     result = super().unsign(signed_value)
kithara_base_1  |   File "/usr/local/lib/python3.9/site-packages/itsdangerous/signer.py", line 240, in unsign
kithara_base_1  |     raise BadSignature(f"No {self.sep!r} found in value")
kithara_base_1  | itsdangerous.exc.BadSignature: No b'.' found in value

**Comment by dudil** [comment] 2021-06-03 06:55
Thank @jlerman44 !

Can you send me your installed packages list? I will check it out.
``` bash
pip list
```

Also what version of python are you using?
Are you running this on Mac or Linux? and what OS/Version?

**Comment by jlerman44** [comment] 2021-06-03 14:33
Hi dudil,

I have a Mac OS X 11.4 host, but running docker with Linux python:3.9-rc-slim inside.

Package                  Version
------------------------ ---------
aiofiles                 0.7.0
anyio                    3.1.0
argon2-cffi              20.1.0
asgiref                  3.3.4
async-generator          1.10
attrs                    21.2.0
azure-core               1.14.0
azure-storage-file-share 12.2.0
Babel                    2.9.1
backcall                 0.2.0
bleach                   3.3.0
certifi                  2021.5.30
cffi                     1.14.5
chardet                  3.0.4
click                    8.0.1
cryptography             3.4.7
decorator                5.0.9
defusedxml               0.7.1
ecdsa                    0.14.1
entrypoints              0.3
fastapi                  0.63.0
fastapi-msal             0.1.5
gunicorn                 19.9.0
h11                      0.12.0
httptools                0.2.0
idna                     2.8
iniconfig                1.1.1
ipykernel                5.5.5
ipython                  7.24.1
ipython-genutils         0.2.0
isodate                  0.6.0
itsdangerous             2.0.1
jedi                     0.18.0
Jinja2                   3.0.1
json5                    0.9.5
jsonschema               3.2.0
jupyter-client           6.1.12
jupyter-core             4.7.1
jupyter-server           1.8.0
jupyterlab               3.0.16
jupyterlab-pygments      0.1.2
jupyterlab-server        2.6.0
MarkupSafe               2.0.1
matplotlib-inline        0.1.2
mistune                  0.8.4
msal                     1.12.0
msrest                   0.6.21
nbclassic                0.3.1
nbclient                 0.5.3
nbconvert                6.0.7
nbformat                 5.1.3
nest-asyncio             1.5.1
nose                     1.3.7
notebook                 6.4.0
numpy                    1.20.3
oauthlib                 3.1.1
packaging                20.9
pandas                   1.2.4
pandocfilters            1.4.3
parso                    0.8.2
pexpect                  4.8.0
pickleshare              0.7.5
pip                      21.1.2
pluggy                   0.13.1
prometheus-client        0.11.0
prompt-toolkit           3.0.18
ptyprocess               0.7.0
py                       1.10.0
pyasn1                   0.4.8
pycparser                2.20
pydantic                 1.8.2
Pygments                 2.9.0
PyJWT                    1.7.1
pyparsing                2.4.7
pyrsistent               0.17.3
pytest                   6.1.0
python-dateutil          2.8.1
python-dotenv            0.17.1
python-jose              3.2.0
python-multipart         0.0.5
pytz                     2021.1
PyYAML                   5.4.1
pyzmq                    22.1.0
requests                 2.21.0
requests-oauthlib        1.3.0
rsa                      4.7.2
Send2Trash               1.5.0
setuptools               50.3.0
six                      1.16.0
sniffio                  1.2.0
starlette                0.13.6
terminado                0.10.0
testpath                 0.5.0
toml                     0.10.2
tornado                  6.1
traitlets                5.0.5
typing-extensions        3.10.0.0
urllib3                  1.24.3
uuid                     1.30
uvicorn                  0.14.0
uvloop                   0.15.2
validate-email           1.3
watchgod                 0.7
wcwidth                  0.2.5
webencodings             0.5.1
websocket-client         1.0.1
websockets               9.1
Werkzeug                 1.0.1
wheel                    0.35.1
xlrd                     1.2.0
XlsxWriter               1.3.3

**Comment by jlerman44** [comment] 2021-06-03 15:02
By the way, I came from https://github.com/tiangolo/fastapi/issues/754#issuecomment-808705933 where you eloquently described the problem with session data not being persistent to followup calls....  I'm excited for your project here :)

**Comment by dudil** [comment] 2021-06-03 16:31
Since you mentioned that you were taking the example as is - I do hope that on the following line you __did changed__ the secret:
```python
app.add_middleware(SessionMiddleware, secret_key="SOME_SSH_KEY_ONLY_YOU_KNOW")  # replace with your own!!!
```

Anyway - can you try maybe a different secret? I suspect this might be the root cause of the exception.

> fastapi_app:app is the code from your README. I removed one stray ")" going from:

Thanks! I Will fix that 😊
> By the way, I came from tiangolo/fastapi#754 (comment) where you eloquently described the problem with session data not being persistent to followup calls.... I'm excited for your project here :)

Thank you for that, and your help here is very much appreciated!
This version includes a nice workaround to this issue by using both the __fastapi__ approach of session cookie and __msal__ approach of local datastore.
You remind me that I need to add a support for external cache datastore.... 😅

**Comment by jlerman44** [comment] 2021-06-03 16:55
It works!  I am not sure what I changed, but now I am on a PC using docker. I'll check again later and get back to you. I also had to set a redirect URL in my Azure App Registration to "<host>/docs/oauth2-redirect".

**Comment by dudil** [comment] 2021-06-03 19:40
Great - happy to hear that.
I'm closing the ticket but if you find the source of it or have any other insights, feel free to reopen it.

Thanks!

**Closed by dudil** 2021-06-03 19:40 UTC

**Comment by jlerman44** [comment] 2021-06-04 04:32
@dudil , Still failing on Mac OS X 11.4. Can we reopen for that purpose?

**Comment by jlerman44** [comment] 2021-06-04 04:37
Never-mind!  I just had to clear my browser cache.. Silly me.
